<?php
include('_includes/masthead.html');
include('_includes/landing.html');
include('_includes/_fund-strategy.html');
include('_includes/_intro-2col-2row.html');
include('_includes/_why-aranca-c.html');
include('_includes/_content-row-grid.html');
include('_includes/_sol-portfolio-b.html');
include('_includes/_client-logos.html');
include('_includes/contact.html');
include('_includes/_CTA-form.html');
?>